[package]
name = "my-site"
version = "0.1.0"
edition = "2024"

[dependencies]
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["KeyboardEvent", "console"] }
