[package]
name = "my-site"
version = "0.1.0"
edition = "2024"

[dependencies]
yew = { version = "0.21", features = ["csr"] }
yew-router = "0.18"
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["KeyboardEvent","console"] }
